name: UI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ui:
    name: Check UI with node v${{ matrix.node-version }}
    runs-on: ubuntu-20.04
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: ui/pnpm-lock.yaml

      - name: 📥 Install dependencies
        working-directory: ui
        run: pnpm i

      - name: 🔬 Type check
        working-directory: ui
        run: pnpm type-check

      - name: 🔧 Build
        working-directory: ui
        run: pnpm build
